on:
  push:
    branches:
      - master
  pull_request:

name: Quality Assurance

jobs:
  phpstan:
    name: PHPStan

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: "actions/checkout@v2"

      - name: Install composer packages
        uses: "ramsey/composer-install@v1"

      - name: PHPStan
        uses: "docker://oskarstark/phpstan-ga"
        with:
          args: analyse

  phpunit:
    name: PHPUnit

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: "actions/checkout@v2"

      - name: Install composer packages
        uses: "ramsey/composer-install@v1"

      - name: PHPUnit
        uses: "php-actions/phpunit@v3"
